[BRD-144] - Loading Page
mia-platform/microlc pull request #30
Opened 2021-04-19 15:55 UTC by Evange95

created loading page and swapped with skeleton

2021-04-19 15:59 UTC, ilteoood requested changes

2021-04-19 15:59 UTC, ilteoood commented on packages/fe-container/src/components/loading-animation/LoadingAnimation.less
> +            fill: var(--microlc-primary-color);;
use a single ;

2021-04-19 15:59 UTC, ilteoood commented on packages/fe-container/src/components/loading-animation/LoadingAnimation.less
> +            fill: var(--microlc-primary-color);;
use a single ;

2021-04-19 15:59 UTC, ilteoood commented on packages/fe-container/src/components/loading-animation/LoadingAnimation.less
> +            fill: var(--microlc-primary-color);;
use a single ;

2021-04-19 15:59 UTC, ilteoood commented on packages/fe-container/src/components/loading-animation/LoadingAnimation.less
> +        fill :var(--microlc-primary-color-tint-89)
use a single ;

2021-04-19 15:59 UTC, ilteoood commented on packages/fe-container/src/components/loading-animation/LoadingAnimation.less
> +            fill: var(--microlc-primary-color);;
use a single ;

(check the rest of the file)

2021-04-19 15:59 UTC, ilteoood commented on packages/fe-container/src/components/loading-animation/LoadingAnimation.test.tsx
> +describe('ErrorPageContainer tests', () => {
this is not a test for error page container :smiley:

2021-04-19 15:59 UTC, ilteoood commented on packages/fe-container/src/components/loading-animation/LoadingAnimation.tsx
> +import {ReactComponent as SvgAnimation} from './assets/LoadingAnimation.svg'
use a space between these 2 imports

2021-04-19 15:59 UTC, ilteoood commented on packages/fe-container/src/containers/launcher/Launcher.tsx
> +        <LoadingAnimation /> :
please re-align

2021-04-19 21:09 UTC, ilteoood requested changes

2021-04-19 21:09 UTC, ilteoood commented on packages/fe-container/src/components/loading-animation/LoadingAnimation.less
> +        fill :var(--microlc-primary-color-tint-89)
here is missing the semi column

2021-04-19 21:09 UTC, ilteoood commented on packages/fe-container/src/components/loading-animation/LoadingAnimation.less
> +        fill :var(--microlc-primary-color-tint-89)
semicolumn missing

2021-04-19 21:09 UTC, ilteoood commented on packages/fe-container/src/components/loading-animation/LoadingAnimation.test.tsx
> +import {LoadingAnimation} from './LoadingAnimation'
insert a space between these 2 imports

2021-04-20 09:20 UTC, epessina approved these changes

2021-04-20 09:20 UTC, merged