[BRD-166-167] - Help Button and Hide Burger Icon
mia-platform/microlc pull request #32
Opened 2021-04-20 15:07 UTC by Evange95

implemented the help button with redirection to the doc page and burger icon is not rendered when plugin list is empty

2021-04-20 15:18 UTC, ilteoood requested changes

2021-04-20 15:18 UTC, ilteoood commented on packages/fe-container/src/components/help-icon/HelpIcon.tsx
> +  const clickHandler = () => {
I suggest to extract this function outside the component, because it doesn't depend on the component rendering

2021-04-20 15:18 UTC, ilteoood commented on packages/fe-container/src/components/top-bar/TopBar.test.tsx
> +    const theming = {
if theming is the same between all the tests, please extract it at describe level

2021-04-20 15:18 UTC, ilteoood commented on packages/fe-container/src/components/top-bar/TopBar.test.tsx
> +        plugins: [{
same for plugins

2021-04-20 15:18 UTC, ilteoood commented on packages/fe-container/src/components/top-bar/TopBar.tsx
> +import {HelpIcon} from '@components/help-icon/HelpIcon'
antd is an external library, this is not the right place to import it :smile_cat:

2021-04-20 15:18 UTC, ilteoood commented on packages/fe-container/src/components/top-bar/TopBar.tsx
> +        <Divider className='topBar_divider' type="vertical"/>
the divider should be inserted only if user is logged! (see use.name && ... condition)

2021-04-21 07:39 UTC, epessina requested changes

2021-04-21 07:39 UTC, epessina commented on packages/fe-container/src/components/help-icon/HelpIcon.less
> +.help_button_container {
Reindent everything with 2 spaces

2021-04-21 07:39 UTC, epessina commented on packages/fe-container/src/components/help-icon/HelpIcon.less
> +    height         : 100%;
Align `:` to the left

2021-04-21 07:39 UTC, epessina commented on packages/fe-container/src/components/help-icon/HelpIcon.less
> +}
Add a newline at the end of the file

2021-04-21 07:39 UTC, epessina commented on packages/fe-container/src/components/help-icon/HelpIcon.tsx
> +  window.open('https://docs.mia-platform.eu/docs/business_suite/microlc/overview')
This should be extracted in a constant `DOCUMENTATION_URL`

2021-04-21 07:39 UTC, epessina commented on packages/fe-container/src/components/help-icon/HelpIcon.tsx
> +        <i className='topBar_documentationLink fas fa-question-circle fa-lg'/>
To align with mockups, use `fas fa-question-circle`

2021-04-21 07:39 UTC, epessina commented on .vscode/settings.json
> +{
The folder `.vscode` should not be pushed. Add it to the `.gitignore` and delete this folder

2021-04-21 07:39 UTC, epessina commented on packages/fe-container/src/components/help-icon/HelpIcon.less
> +  justify-content: center;
Add `cursor: pointer;`

2021-04-21 08:13 UTC, epessina requested changes

2021-04-21 08:13 UTC, epessina commented on packages/fe-container/src/components/top-bar/TopBar.tsx
> +  const mustShowBurgerIcon = (configuration?.plugins || []).length > 0
```suggestion
  const mustShowBurgerIcon = (configuration?.plugins || []).length > 1
```

The icon should be visible if we have at least 2 plugins, not al least 1.

2021-04-21 08:28 UTC, merged